# -*- coding: utf-8 -*-
"""DL LAB 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1poH3MKy-kX0tWCaU9ylTMReRHaEP_xB1
"""

#implemention of and gate, or gate using MC CULLOH PITS NEURON
import numpy as np
def mc_pits(x,w,theta):
  return 1 if np.dot(w,x)>= theta else 0
print("And Gate")
w=np.array([1,1])
theta_forAND_gate = 2
for x in [(0,0),(0,1),(1,0),(1,1)]:
  print(mc_pits(np.array(x),w,theta_forAND_gate))

import numpy as np
def mc_pits(x,w,theta):
  return 1 if np.dot(w,x)>= theta else 0
print("And Gate")
w=np.array([1,1,1])
theta_forAND_gate = 3
for x in [(0,0,0),(0,0,1),(0,1,0),(0,1,1),(1,0,0),(1,0,1),(1,1,0),(1,1,1)]:
  print(mc_pits(np.array(x),w,theta_forAND_gate))

import numpy as np
def mc_pits(x,w,theta):
  return 1 if np.dot(w,x)>= theta else 0
print("OR Gate")
w=np.array([1,1])
theta_forOR_gate = 1
for x in [(0,0),(0,1),(1,0),(1,1)]:
  print(mc_pits(np.array(x),w,theta_forOR_gate))

import numpy as np
def mc_pitts(x,w,theta):
  return 1 if np.dot(w,x)>= theta else 0
print("OR GATE")
w=np.array([1,1,1])
theta_forOR_gate=1
for x in [(0,0,0),(0,0,1),(0,1,0),(0,1,1),(1,0,0),(1,0,1),(1,1,0),(1,1,1)]:
  print(mc_pits(np.array(x),w,theta_forOR_gate))

#perceptron learning algorithm
import numpy as np
step = lambda x: 1 if x >= 0 else 0
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,0,0,1])
w = np.zeros(2)
b = 0
for _ in range(10):
    for i in range(len(X)):
        y_pred = step(np.dot(X[i], w) + b)
        w = w + (y[i] - y_pred) * X[i]
        b = b + (y[i] - y_pred)
for x in X:
    print(step(np.dot(x, w) + b))

#implementation on artifical neurons
import numpy as np
def art_neuron(w, x, b, activation):
    z = np.dot(w, x) + b
    if activation == 'step':
        return 1 if z >= 0 else 0
    elif activation == 'sigmoid':
        return 1 / (1 + np.exp(-z))
    elif activation == 'relu':
        return max(0, z)
x = np.array([0.8, 0.5])
w = np.array([1, 0.4])
b = -0.3
print("Step output:", art_neuron(w, x, b, 'step'))
print("Sigmoid output:", art_neuron(w, x, b, 'sigmoid'))
print("Relu output:", art_neuron(w, x, b, 'relu'))
print("code run by Amishi 1/23/SET/BCS/432")